# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zYYeeORBWs4sO_GmDfqGgU_AMvkhvWsB
"""

! pip install streamlit
import streamlit as st
import pandas as pd
import joblib

# Load the trained model
model = joblib.load('D:\Logistic Regression\logistic_regression_model.pkl')

# Define the app
st.title("Titanic Survival Prediction")

# User inputs
pclass = st.selectbox("Passenger Class", [1, 2, 3])
sex = st.selectbox("Sex", ["Female", "Male"])
age = st.number_input("Age", min_value=0, max_value=100, value=30)
sibsp = st.number_input("Number of Siblings/Spouses Aboard", min_value=0, max_value=10, value=0)
parch = st.number_input("Number of Parents/Children Aboard", min_value=0, max_value=10, value=0)
fare = st.number_input("Fare", min_value=0.0, max_value=500.0, value=50.0)
embarked = st.selectbox("Port of Embarkation", ["Cherbourg", "Queenstown", "Southampton"])

# Map inputs to model format
sex_encoded = 1 if sex == "Male" else 0
embarked_encoded = {
    "Cherbourg": [1, 0],
    "Queenstown": [0, 1],
    "Southampton": [0, 0]
}[embarked]

# Prepare input data
input_data = pd.DataFrame({
    'Pclass': [pclass],
    'Sex': [sex_encoded],
    'Age': [age],
    'SibSp': [sibsp],
    'Parch': [parch],
    'Fare': [fare],
    'Embarked_Q': [embarked_encoded[0]],
    'Embarked_S': [embarked_encoded[1]]
})

# Predict
if st.button("Predict"):
    prediction = model.predict(input_data)[0]
    probability = model.predict_proba(input_data)[0][1]
    result = "Survived" if prediction == 1 else "Did Not Survive"
    st.write(f"Prediction: {result}")
    st.write(f"Probability of Survival: {probability:.2f}")

